[package]
name = "riscv-rt"
version = "0.7.1"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
riscv-rt-new = { path = "..", package = "riscv-rt", version = "0.8" }

[features]
inline-asm = []
